# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 483)
        MainWindow.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    spacing: 1px;\n"
"}\n"
"QRadioButton::indicator{\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 671, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.gbNavig = QtWidgets.QGroupBox(self.tabGeneral)
        self.gbNavig.setGeometry(QtCore.QRect(10, 0, 301, 361))
        self.gbNavig.setStyleSheet("")
        self.gbNavig.setObjectName("gbNavig")
        self.navBtnExecPath = QtWidgets.QPushButton(self.gbNavig)
        self.navBtnExecPath.setGeometry(QtCore.QRect(210, 210, 81, 31))
        self.navBtnExecPath.setObjectName("navBtnExecPath")
        self.navTxtStartPose = QtWidgets.QLineEdit(self.gbNavig)
        self.navTxtStartPose.setGeometry(QtCore.QRect(89, 180, 121, 23))
        self.navTxtStartPose.setObjectName("navTxtStartPose")
        self.navTxtGoalPose = QtWidgets.QLineEdit(self.gbNavig)
        self.navTxtGoalPose.setGeometry(QtCore.QRect(89, 210, 121, 23))
        self.navTxtGoalPose.setObjectName("navTxtGoalPose")
        self.navLblStartPose = QtWidgets.QLabel(self.gbNavig)
        self.navLblStartPose.setGeometry(QtCore.QRect(10, 180, 81, 17))
        self.navLblStartPose.setObjectName("navLblStartPose")
        self.navBtnCalcPath = QtWidgets.QPushButton(self.gbNavig)
        self.navBtnCalcPath.setGeometry(QtCore.QRect(214, 170, 81, 31))
        self.navBtnCalcPath.setObjectName("navBtnCalcPath")
        self.navLblGoalPose = QtWidgets.QLabel(self.gbNavig)
        self.navLblGoalPose.setGeometry(QtCore.QRect(10, 210, 81, 17))
        self.navLblGoalPose.setObjectName("navLblGoalPose")
        self.navLblMove = QtWidgets.QLabel(self.gbNavig)
        self.navLblMove.setGeometry(QtCore.QRect(10, 245, 101, 17))
        self.navLblMove.setObjectName("navLblMove")
        self.navTxtMove = QtWidgets.QLineEdit(self.gbNavig)
        self.navTxtMove.setGeometry(QtCore.QRect(110, 245, 181, 27))
        self.navTxtMove.setObjectName("navTxtMove")
        self.txtLinearX = QtWidgets.QLineEdit(self.gbNavig)
        self.txtLinearX.setGeometry(QtCore.QRect(210, 25, 81, 27))
        self.txtLinearX.setObjectName("txtLinearX")
        self.label_2 = QtWidgets.QLabel(self.gbNavig)
        self.label_2.setGeometry(QtCore.QRect(190, 30, 16, 17))
        self.label_2.setObjectName("label_2")
        self.btnTurnRight = QtWidgets.QPushButton(self.gbNavig)
        self.btnTurnRight.setGeometry(QtCore.QRect(125, 50, 50, 40))
        self.btnTurnRight.setText("")
        self.btnTurnRight.setIconSize(QtCore.QSize(32, 32))
        self.btnTurnRight.setObjectName("btnTurnRight")
        self.btnFwd = QtWidgets.QPushButton(self.gbNavig)
        self.btnFwd.setGeometry(QtCore.QRect(65, 20, 50, 40))
        self.btnFwd.setText("")
        self.btnFwd.setIconSize(QtCore.QSize(32, 32))
        self.btnFwd.setObjectName("btnFwd")
        self.btnTurnLeft = QtWidgets.QPushButton(self.gbNavig)
        self.btnTurnLeft.setGeometry(QtCore.QRect(5, 50, 50, 40))
        self.btnTurnLeft.setText("")
        self.btnTurnLeft.setIconSize(QtCore.QSize(32, 32))
        self.btnTurnLeft.setObjectName("btnTurnLeft")
        self.txtAngular = QtWidgets.QLineEdit(self.gbNavig)
        self.txtAngular.setGeometry(QtCore.QRect(210, 85, 81, 27))
        self.txtAngular.setObjectName("txtAngular")
        self.label_3 = QtWidgets.QLabel(self.gbNavig)
        self.label_3.setGeometry(QtCore.QRect(190, 60, 16, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.gbNavig)
        self.label_4.setGeometry(QtCore.QRect(190, 90, 16, 17))
        self.label_4.setObjectName("label_4")
        self.btnBwd = QtWidgets.QPushButton(self.gbNavig)
        self.btnBwd.setGeometry(QtCore.QRect(65, 80, 50, 40))
        self.btnBwd.setText("")
        self.btnBwd.setIconSize(QtCore.QSize(32, 32))
        self.btnBwd.setObjectName("btnBwd")
        self.btnCmdVel = QtWidgets.QPushButton(self.gbNavig)
        self.btnCmdVel.setGeometry(QtCore.QRect(190, 115, 101, 27))
        self.btnCmdVel.setObjectName("btnCmdVel")
        self.txtLinearY = QtWidgets.QLineEdit(self.gbNavig)
        self.txtLinearY.setGeometry(QtCore.QRect(210, 55, 81, 27))
        self.txtLinearY.setObjectName("txtLinearY")
        self.btnStop = QtWidgets.QPushButton(self.gbNavig)
        self.btnStop.setGeometry(QtCore.QRect(10, 280, 281, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 94, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 94, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 148, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 94, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.btnStop.setPalette(palette)
        self.btnStop.setObjectName("btnStop")
        self.btnRight = QtWidgets.QPushButton(self.gbNavig)
        self.btnRight.setGeometry(QtCore.QRect(120, 100, 50, 31))
        self.btnRight.setText("")
        self.btnRight.setIconSize(QtCore.QSize(32, 32))
        self.btnRight.setObjectName("btnRight")
        self.btnLeft = QtWidgets.QPushButton(self.gbNavig)
        self.btnLeft.setGeometry(QtCore.QRect(10, 100, 50, 31))
        self.btnLeft.setText("")
        self.btnLeft.setIconSize(QtCore.QSize(32, 32))
        self.btnLeft.setObjectName("btnLeft")
        self.gbHead = QtWidgets.QGroupBox(self.tabGeneral)
        self.gbHead.setGeometry(QtCore.QRect(320, 0, 301, 81))
        self.gbHead.setObjectName("gbHead")
        self.hdTxtPan = QtWidgets.QDoubleSpinBox(self.gbHead)
        self.hdTxtPan.setGeometry(QtCore.QRect(40, 20, 81, 25))
        self.hdTxtPan.setKeyboardTracking(False)
        self.hdTxtPan.setDecimals(4)
        self.hdTxtPan.setMinimum(-1.5708)
        self.hdTxtPan.setMaximum(1.5708)
        self.hdTxtPan.setSingleStep(0.1)
        self.hdTxtPan.setObjectName("hdTxtPan")
        self.hdLblPan = QtWidgets.QLabel(self.gbHead)
        self.hdLblPan.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.hdLblPan.setObjectName("hdLblPan")
        self.label = QtWidgets.QLabel(self.gbHead)
        self.label.setGeometry(QtCore.QRect(10, 45, 31, 16))
        self.label.setObjectName("label")
        self.hdTxtTilt = QtWidgets.QDoubleSpinBox(self.gbHead)
        self.hdTxtTilt.setGeometry(QtCore.QRect(40, 45, 81, 25))
        self.hdTxtTilt.setKeyboardTracking(False)
        self.hdTxtTilt.setDecimals(4)
        self.hdTxtTilt.setMinimum(-1.5)
        self.hdTxtTilt.setMaximum(0.3)
        self.hdTxtTilt.setSingleStep(0.1)
        self.hdTxtTilt.setObjectName("hdTxtTilt")
        self.hdLblHeadPoseLbl = QtWidgets.QLabel(self.gbHead)
        self.hdLblHeadPoseLbl.setGeometry(QtCore.QRect(130, 20, 91, 16))
        self.hdLblHeadPoseLbl.setObjectName("hdLblHeadPoseLbl")
        self.hdTxtPredefined = QtWidgets.QLineEdit(self.gbHead)
        self.hdTxtPredefined.setGeometry(QtCore.QRect(130, 40, 161, 27))
        self.hdTxtPredefined.setObjectName("hdTxtPredefined")
        self.gbSpeech = QtWidgets.QGroupBox(self.tabGeneral)
        self.gbSpeech.setGeometry(QtCore.QRect(320, 160, 341, 201))
        self.gbSpeech.setObjectName("gbSpeech")
        self.spgTxtSay = QtWidgets.QLineEdit(self.gbSpeech)
        self.spgTxtSay.setGeometry(QtCore.QRect(90, 20, 241, 23))
        self.spgTxtSay.setObjectName("spgTxtSay")
        self.spgLabel = QtWidgets.QLabel(self.gbSpeech)
        self.spgLabel.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.spgLabel.setObjectName("spgLabel")
        self.sprLabel = QtWidgets.QLabel(self.gbSpeech)
        self.sprLabel.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.sprLabel.setObjectName("sprLabel")
        self.sprTxtFakeRecog = QtWidgets.QLineEdit(self.gbSpeech)
        self.sprTxtFakeRecog.setGeometry(QtCore.QRect(90, 50, 241, 23))
        self.sprTxtFakeRecog.setObjectName("sprTxtFakeRecog")
        self.laLblAngles6_5 = QtWidgets.QLabel(self.gbSpeech)
        self.laLblAngles6_5.setGeometry(QtCore.QRect(10, 80, 81, 17))
        self.laLblAngles6_5.setObjectName("laLblAngles6_5")
        self.sprLblLastRecog = QtWidgets.QLabel(self.gbSpeech)
        self.sprLblLastRecog.setGeometry(QtCore.QRect(10, 100, 321, 61))
        self.sprLblLastRecog.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sprLblLastRecog.setWordWrap(True)
        self.sprLblLastRecog.setObjectName("sprLblLastRecog")
        self.gbHead_2 = QtWidgets.QGroupBox(self.tabGeneral)
        self.gbHead_2.setGeometry(QtCore.QRect(320, 90, 301, 71))
        self.gbHead_2.setObjectName("gbHead_2")
        self.torTxtPos = QtWidgets.QDoubleSpinBox(self.gbHead_2)
        self.torTxtPos.setGeometry(QtCore.QRect(10, 40, 111, 25))
        self.torTxtPos.setKeyboardTracking(False)
        self.torTxtPos.setDecimals(4)
        self.torTxtPos.setMinimum(0.02)
        self.torTxtPos.setMaximum(0.28)
        self.torTxtPos.setSingleStep(0.02)
        self.torTxtPos.setObjectName("torTxtPos")
        self.hdLblPan_2 = QtWidgets.QLabel(self.gbHead_2)
        self.hdLblPan_2.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.hdLblPan_2.setObjectName("hdLblPan_2")
        self.hdLblHeadPoseLbl_2 = QtWidgets.QLabel(self.gbHead_2)
        self.hdLblHeadPoseLbl_2.setGeometry(QtCore.QRect(140, 20, 91, 16))
        self.hdLblHeadPoseLbl_2.setObjectName("hdLblHeadPoseLbl_2")
        self.torTxtPredefined = QtWidgets.QLineEdit(self.gbHead_2)
        self.torTxtPredefined.setGeometry(QtCore.QRect(140, 40, 141, 27))
        self.torTxtPredefined.setObjectName("torTxtPredefined")
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.visBtnFindLines = QtWidgets.QPushButton(self.tab)
        self.visBtnFindLines.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.visBtnFindLines.setObjectName("visBtnFindLines")
        self.visTxtTrainObject = QtWidgets.QLineEdit(self.tab)
        self.visTxtTrainObject.setGeometry(QtCore.QRect(10, 70, 113, 25))
        self.visTxtTrainObject.setObjectName("visTxtTrainObject")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 101, 17))
        self.label_5.setObjectName("label_5")
        self.visBtnRecogObjects = QtWidgets.QPushButton(self.tab)
        self.visBtnRecogObjects.setGeometry(QtCore.QRect(10, 110, 141, 31))
        self.visBtnRecogObjects.setObjectName("visBtnRecogObjects")
        self.visTxtRecognizeObject = QtWidgets.QLineEdit(self.tab)
        self.visTxtRecognizeObject.setGeometry(QtCore.QRect(10, 170, 131, 25))
        self.visTxtRecognizeObject.setObjectName("visTxtRecognizeObject")
        self.visBtnFindHoriPlanes = QtWidgets.QPushButton(self.tab)
        self.visBtnFindHoriPlanes.setGeometry(QtCore.QRect(130, 10, 171, 31))
        self.visBtnFindHoriPlanes.setObjectName("visBtnFindHoriPlanes")
        self.visBtnPointsAbovePlane = QtWidgets.QPushButton(self.tab)
        self.visBtnPointsAbovePlane.setGeometry(QtCore.QRect(350, 10, 121, 41))
        self.visBtnPointsAbovePlane.setObjectName("visBtnPointsAbovePlane")
        self.visBtnEnableHumanPose = QtWidgets.QPushButton(self.tab)
        self.visBtnEnableHumanPose.setGeometry(QtCore.QRect(500, 10, 121, 51))
        self.visBtnEnableHumanPose.setObjectName("visBtnEnableHumanPose")
        self.hriBtnEnableFollowHuman = QtWidgets.QPushButton(self.tab)
        self.hriBtnEnableFollowHuman.setGeometry(QtCore.QRect(500, 80, 121, 51))
        self.hriBtnEnableFollowHuman.setObjectName("hriBtnEnableFollowHuman")
        self.tabWidget.addTab(self.tab, "")
        self.tabSimpleTasks = QtWidgets.QWidget()
        self.tabSimpleTasks.setObjectName("tabSimpleTasks")
        self.tksBtnApproachTable = QtWidgets.QPushButton(self.tabSimpleTasks)
        self.tksBtnApproachTable.setGeometry(QtCore.QRect(20, 20, 111, 51))
        self.tksBtnApproachTable.setObjectName("tksBtnApproachTable")
        self.tksTxtTakeObject = QtWidgets.QLineEdit(self.tabSimpleTasks)
        self.tksTxtTakeObject.setGeometry(QtCore.QRect(20, 110, 113, 25))
        self.tksTxtTakeObject.setObjectName("tksTxtTakeObject")
        self.label_6 = QtWidgets.QLabel(self.tabSimpleTasks)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.label_6.setObjectName("label_6")
        self.tksBtnTakeObject = QtWidgets.QPushButton(self.tabSimpleTasks)
        self.tksBtnTakeObject.setGeometry(QtCore.QRect(140, 100, 71, 41))
        self.tksBtnTakeObject.setObjectName("tksBtnTakeObject")
        self.tksBtnApproachTable_2 = QtWidgets.QPushButton(self.tabSimpleTasks)
        self.tksBtnApproachTable_2.setGeometry(QtCore.QRect(20, 170, 111, 51))
        self.tksBtnApproachTable_2.setObjectName("tksBtnApproachTable_2")
        self.label_9 = QtWidgets.QLabel(self.tabSimpleTasks)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 121, 101))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tabSimpleTasks, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gbNavig_2 = QtWidgets.QGroupBox(self.tab_2)
        self.gbNavig_2.setGeometry(QtCore.QRect(0, 10, 311, 321))
        self.gbNavig_2.setStyleSheet("")
        self.gbNavig_2.setObjectName("gbNavig_2")
        self.laTxtCartesianGoal = QtWidgets.QLineEdit(self.gbNavig_2)
        self.laTxtCartesianGoal.setGeometry(QtCore.QRect(50, 220, 251, 31))
        self.laTxtCartesianGoal.setObjectName("laTxtCartesianGoal")
        self.navLblStartPose_2 = QtWidgets.QLabel(self.gbNavig_2)
        self.navLblStartPose_2.setGeometry(QtCore.QRect(10, 230, 51, 17))
        self.navLblStartPose_2.setObjectName("navLblStartPose_2")
        self.laBtnXp = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnXp.setGeometry(QtCore.QRect(140, 40, 50, 40))
        self.laBtnXp.setIconSize(QtCore.QSize(32, 32))
        self.laBtnXp.setObjectName("laBtnXp")
        self.laBtnYp = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnYp.setGeometry(QtCore.QRect(80, 20, 50, 40))
        self.laBtnYp.setIconSize(QtCore.QSize(32, 32))
        self.laBtnYp.setObjectName("laBtnYp")
        self.laBtnXm = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnXm.setGeometry(QtCore.QRect(20, 40, 50, 40))
        self.laBtnXm.setIconSize(QtCore.QSize(32, 32))
        self.laBtnXm.setObjectName("laBtnXm")
        self.laBtnYm = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnYm.setGeometry(QtCore.QRect(80, 70, 50, 40))
        self.laBtnYm.setIconSize(QtCore.QSize(32, 32))
        self.laBtnYm.setObjectName("laBtnYm")
        self.laLblCurrentX = QtWidgets.QLabel(self.gbNavig_2)
        self.laLblCurrentX.setGeometry(QtCore.QRect(10, 280, 41, 17))
        self.laLblCurrentX.setObjectName("laLblCurrentX")
        self.laBtnZp = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnZp.setGeometry(QtCore.QRect(220, 20, 50, 40))
        self.laBtnZp.setIconSize(QtCore.QSize(32, 32))
        self.laBtnZp.setObjectName("laBtnZp")
        self.laBtnZm = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnZm.setGeometry(QtCore.QRect(220, 70, 50, 40))
        self.laBtnZm.setIconSize(QtCore.QSize(32, 32))
        self.laBtnZm.setObjectName("laBtnZm")
        self.navLblStartPose_3 = QtWidgets.QLabel(self.gbNavig_2)
        self.navLblStartPose_3.setGeometry(QtCore.QRect(20, 300, 21, 17))
        self.navLblStartPose_3.setObjectName("navLblStartPose_3")
        self.navLblStartPose_4 = QtWidgets.QLabel(self.gbNavig_2)
        self.navLblStartPose_4.setGeometry(QtCore.QRect(70, 300, 21, 17))
        self.navLblStartPose_4.setObjectName("navLblStartPose_4")
        self.navLblStartPose_5 = QtWidgets.QLabel(self.gbNavig_2)
        self.navLblStartPose_5.setGeometry(QtCore.QRect(120, 300, 21, 17))
        self.navLblStartPose_5.setObjectName("navLblStartPose_5")
        self.navLblStartPose_6 = QtWidgets.QLabel(self.gbNavig_2)
        self.navLblStartPose_6.setGeometry(QtCore.QRect(170, 300, 21, 17))
        self.navLblStartPose_6.setObjectName("navLblStartPose_6")
        self.navLblStartPose_7 = QtWidgets.QLabel(self.gbNavig_2)
        self.navLblStartPose_7.setGeometry(QtCore.QRect(270, 300, 21, 17))
        self.navLblStartPose_7.setObjectName("navLblStartPose_7")
        self.navLblStartPose_8 = QtWidgets.QLabel(self.gbNavig_2)
        self.navLblStartPose_8.setGeometry(QtCore.QRect(220, 300, 21, 17))
        self.navLblStartPose_8.setObjectName("navLblStartPose_8")
        self.laLblCurrentY = QtWidgets.QLabel(self.gbNavig_2)
        self.laLblCurrentY.setGeometry(QtCore.QRect(60, 280, 41, 17))
        self.laLblCurrentY.setObjectName("laLblCurrentY")
        self.laLblCurrentZ = QtWidgets.QLabel(self.gbNavig_2)
        self.laLblCurrentZ.setGeometry(QtCore.QRect(110, 280, 41, 17))
        self.laLblCurrentZ.setObjectName("laLblCurrentZ")
        self.laLblCurrentRoll = QtWidgets.QLabel(self.gbNavig_2)
        self.laLblCurrentRoll.setGeometry(QtCore.QRect(160, 280, 41, 17))
        self.laLblCurrentRoll.setObjectName("laLblCurrentRoll")
        self.laLblCurrentPitch = QtWidgets.QLabel(self.gbNavig_2)
        self.laLblCurrentPitch.setGeometry(QtCore.QRect(210, 280, 41, 17))
        self.laLblCurrentPitch.setObjectName("laLblCurrentPitch")
        self.laLblCurrentYaw = QtWidgets.QLabel(self.gbNavig_2)
        self.laLblCurrentYaw.setGeometry(QtCore.QRect(260, 280, 41, 17))
        self.laLblCurrentYaw.setObjectName("laLblCurrentYaw")
        self.navLblStartPose_14 = QtWidgets.QLabel(self.gbNavig_2)
        self.navLblStartPose_14.setGeometry(QtCore.QRect(10, 260, 71, 17))
        self.navLblStartPose_14.setObjectName("navLblStartPose_14")
        self.laBtnRollp = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnRollp.setGeometry(QtCore.QRect(40, 130, 50, 31))
        self.laBtnRollp.setIconSize(QtCore.QSize(32, 32))
        self.laBtnRollp.setObjectName("laBtnRollp")
        self.laBtnRollm = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnRollm.setGeometry(QtCore.QRect(40, 170, 50, 31))
        self.laBtnRollm.setIconSize(QtCore.QSize(32, 32))
        self.laBtnRollm.setObjectName("laBtnRollm")
        self.laBtnPitchp = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnPitchp.setGeometry(QtCore.QRect(120, 130, 50, 31))
        self.laBtnPitchp.setIconSize(QtCore.QSize(32, 32))
        self.laBtnPitchp.setObjectName("laBtnPitchp")
        self.laBtnPitchm = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnPitchm.setGeometry(QtCore.QRect(120, 170, 50, 31))
        self.laBtnPitchm.setIconSize(QtCore.QSize(32, 32))
        self.laBtnPitchm.setObjectName("laBtnPitchm")
        self.laBtnYawp = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnYawp.setGeometry(QtCore.QRect(200, 130, 50, 31))
        self.laBtnYawp.setIconSize(QtCore.QSize(32, 32))
        self.laBtnYawp.setObjectName("laBtnYawp")
        self.laBtnYawm = QtWidgets.QPushButton(self.gbNavig_2)
        self.laBtnYawm.setGeometry(QtCore.QRect(200, 170, 50, 31))
        self.laBtnYawm.setIconSize(QtCore.QSize(32, 32))
        self.laBtnYawm.setObjectName("laBtnYawm")
        self.laGbArticular = QtWidgets.QGroupBox(self.tab_2)
        self.laGbArticular.setGeometry(QtCore.QRect(310, 10, 351, 321))
        self.laGbArticular.setObjectName("laGbArticular")
        self.laTxtAngles5 = QtWidgets.QDoubleSpinBox(self.laGbArticular)
        self.laTxtAngles5.setGeometry(QtCore.QRect(220, 30, 121, 31))
        self.laTxtAngles5.setKeyboardTracking(False)
        self.laTxtAngles5.setDecimals(4)
        self.laTxtAngles5.setMinimum(-3.1416)
        self.laTxtAngles5.setMaximum(3.1416)
        self.laTxtAngles5.setSingleStep(0.1)
        self.laTxtAngles5.setObjectName("laTxtAngles5")
        self.laTxtAngles1 = QtWidgets.QDoubleSpinBox(self.laGbArticular)
        self.laTxtAngles1.setGeometry(QtCore.QRect(39, 30, 121, 31))
        self.laTxtAngles1.setKeyboardTracking(False)
        self.laTxtAngles1.setDecimals(4)
        self.laTxtAngles1.setMinimum(-3.1416)
        self.laTxtAngles1.setMaximum(3.1416)
        self.laTxtAngles1.setSingleStep(0.1)
        self.laTxtAngles1.setObjectName("laTxtAngles1")
        self.laTxtAngles4 = QtWidgets.QDoubleSpinBox(self.laGbArticular)
        self.laTxtAngles4.setGeometry(QtCore.QRect(40, 150, 121, 31))
        self.laTxtAngles4.setKeyboardTracking(False)
        self.laTxtAngles4.setDecimals(4)
        self.laTxtAngles4.setMinimum(-3.1416)
        self.laTxtAngles4.setMaximum(3.1416)
        self.laTxtAngles4.setSingleStep(0.1)
        self.laTxtAngles4.setObjectName("laTxtAngles4")
        self.laLblAngles2_3 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblAngles2_3.setGeometry(QtCore.QRect(10, 80, 41, 17))
        self.laLblAngles2_3.setObjectName("laLblAngles2_3")
        self.laLblAngles6_6 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblAngles6_6.setGeometry(QtCore.QRect(181, 80, 41, 17))
        self.laLblAngles6_6.setObjectName("laLblAngles6_6")
        self.laLblAngles5_3 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblAngles5_3.setGeometry(QtCore.QRect(181, 40, 41, 17))
        self.laLblAngles5_3.setObjectName("laLblAngles5_3")
        self.laTxtAngles6 = QtWidgets.QDoubleSpinBox(self.laGbArticular)
        self.laTxtAngles6.setGeometry(QtCore.QRect(220, 70, 121, 31))
        self.laTxtAngles6.setKeyboardTracking(False)
        self.laTxtAngles6.setDecimals(4)
        self.laTxtAngles6.setMinimum(-3.1416)
        self.laTxtAngles6.setMaximum(3.1416)
        self.laTxtAngles6.setSingleStep(0.1)
        self.laTxtAngles6.setObjectName("laTxtAngles6")
        self.laTxtAngles2 = QtWidgets.QDoubleSpinBox(self.laGbArticular)
        self.laTxtAngles2.setGeometry(QtCore.QRect(39, 70, 121, 31))
        self.laTxtAngles2.setKeyboardTracking(False)
        self.laTxtAngles2.setDecimals(4)
        self.laTxtAngles2.setMinimum(-3.1416)
        self.laTxtAngles2.setMaximum(3.1416)
        self.laTxtAngles2.setSingleStep(0.1)
        self.laTxtAngles2.setProperty("value", 0.0)
        self.laTxtAngles2.setObjectName("laTxtAngles2")
        self.laTxtAngles7 = QtWidgets.QDoubleSpinBox(self.laGbArticular)
        self.laTxtAngles7.setGeometry(QtCore.QRect(220, 110, 121, 31))
        self.laTxtAngles7.setKeyboardTracking(False)
        self.laTxtAngles7.setDecimals(4)
        self.laTxtAngles7.setMinimum(-3.1416)
        self.laTxtAngles7.setMaximum(3.1416)
        self.laTxtAngles7.setSingleStep(0.1)
        self.laTxtAngles7.setObjectName("laTxtAngles7")
        self.laLblAngles4_3 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblAngles4_3.setGeometry(QtCore.QRect(10, 160, 41, 17))
        self.laLblAngles4_3.setObjectName("laLblAngles4_3")
        self.laTxtAngles3 = QtWidgets.QDoubleSpinBox(self.laGbArticular)
        self.laTxtAngles3.setGeometry(QtCore.QRect(39, 110, 121, 31))
        self.laTxtAngles3.setKeyboardTracking(False)
        self.laTxtAngles3.setDecimals(4)
        self.laTxtAngles3.setMinimum(-3.1416)
        self.laTxtAngles3.setMaximum(3.1416)
        self.laTxtAngles3.setSingleStep(0.1)
        self.laTxtAngles3.setObjectName("laTxtAngles3")
        self.laLblAngles1_3 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblAngles1_3.setGeometry(QtCore.QRect(10, 40, 41, 17))
        self.laLblAngles1_3.setObjectName("laLblAngles1_3")
        self.laLblAngles3_3 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblAngles3_3.setGeometry(QtCore.QRect(10, 120, 41, 17))
        self.laLblAngles3_3.setObjectName("laLblAngles3_3")
        self.laTxtArticularGoal = QtWidgets.QLineEdit(self.laGbArticular)
        self.laTxtArticularGoal.setGeometry(QtCore.QRect(50, 220, 291, 31))
        self.laTxtArticularGoal.setText("")
        self.laTxtArticularGoal.setObjectName("laTxtArticularGoal")
        self.hdLblHeadPoseLbl_4 = QtWidgets.QLabel(self.laGbArticular)
        self.hdLblHeadPoseLbl_4.setGeometry(QtCore.QRect(10, 230, 51, 16))
        self.hdLblHeadPoseLbl_4.setObjectName("hdLblHeadPoseLbl_4")
        self.laLblAngles6_7 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblAngles6_7.setGeometry(QtCore.QRect(181, 160, 41, 17))
        self.laLblAngles6_7.setObjectName("laLblAngles6_7")
        self.laTxtAnglesG = QtWidgets.QDoubleSpinBox(self.laGbArticular)
        self.laTxtAnglesG.setGeometry(QtCore.QRect(221, 150, 121, 31))
        self.laTxtAnglesG.setKeyboardTracking(False)
        self.laTxtAnglesG.setDecimals(4)
        self.laTxtAnglesG.setMinimum(-3.1416)
        self.laTxtAnglesG.setMaximum(3.1416)
        self.laTxtAnglesG.setSingleStep(0.1)
        self.laTxtAnglesG.setObjectName("laTxtAnglesG")
        self.laLblAngles0_4 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblAngles0_4.setGeometry(QtCore.QRect(181, 120, 41, 17))
        self.laLblAngles0_4.setObjectName("laLblAngles0_4")
        self.navLblStartPose_27 = QtWidgets.QLabel(self.laGbArticular)
        self.navLblStartPose_27.setGeometry(QtCore.QRect(220, 300, 21, 17))
        self.navLblStartPose_27.setObjectName("navLblStartPose_27")
        self.navLblStartPose_23 = QtWidgets.QLabel(self.laGbArticular)
        self.navLblStartPose_23.setGeometry(QtCore.QRect(20, 300, 21, 17))
        self.navLblStartPose_23.setObjectName("navLblStartPose_23")
        self.navLblStartPose_15 = QtWidgets.QLabel(self.laGbArticular)
        self.navLblStartPose_15.setGeometry(QtCore.QRect(10, 260, 71, 17))
        self.navLblStartPose_15.setObjectName("navLblStartPose_15")
        self.navLblStartPose_20 = QtWidgets.QLabel(self.laGbArticular)
        self.navLblStartPose_20.setGeometry(QtCore.QRect(120, 300, 21, 17))
        self.navLblStartPose_20.setObjectName("navLblStartPose_20")
        self.laLblCurrentQ6 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblCurrentQ6.setGeometry(QtCore.QRect(260, 280, 41, 17))
        self.laLblCurrentQ6.setObjectName("laLblCurrentQ6")
        self.navLblStartPose_24 = QtWidgets.QLabel(self.laGbArticular)
        self.navLblStartPose_24.setGeometry(QtCore.QRect(170, 300, 21, 17))
        self.navLblStartPose_24.setObjectName("navLblStartPose_24")
        self.laLblCurrentQ2 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblCurrentQ2.setGeometry(QtCore.QRect(60, 280, 41, 17))
        self.laLblCurrentQ2.setObjectName("laLblCurrentQ2")
        self.laLblCurrentQ4 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblCurrentQ4.setGeometry(QtCore.QRect(160, 280, 41, 17))
        self.laLblCurrentQ4.setObjectName("laLblCurrentQ4")
        self.navLblStartPose_19 = QtWidgets.QLabel(self.laGbArticular)
        self.navLblStartPose_19.setGeometry(QtCore.QRect(70, 300, 21, 17))
        self.navLblStartPose_19.setObjectName("navLblStartPose_19")
        self.laLblCurrentQ3 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblCurrentQ3.setGeometry(QtCore.QRect(110, 280, 41, 17))
        self.laLblCurrentQ3.setObjectName("laLblCurrentQ3")
        self.laLblCurrentQ1 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblCurrentQ1.setGeometry(QtCore.QRect(10, 280, 41, 17))
        self.laLblCurrentQ1.setObjectName("laLblCurrentQ1")
        self.laLblCurrentQ5 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblCurrentQ5.setGeometry(QtCore.QRect(210, 280, 41, 17))
        self.laLblCurrentQ5.setObjectName("laLblCurrentQ5")
        self.navLblStartPose_25 = QtWidgets.QLabel(self.laGbArticular)
        self.navLblStartPose_25.setGeometry(QtCore.QRect(270, 300, 21, 17))
        self.navLblStartPose_25.setObjectName("navLblStartPose_25")
        self.laLblCurrentQ7 = QtWidgets.QLabel(self.laGbArticular)
        self.laLblCurrentQ7.setGeometry(QtCore.QRect(310, 280, 41, 17))
        self.laLblCurrentQ7.setObjectName("laLblCurrentQ7")
        self.navLblStartPose_26 = QtWidgets.QLabel(self.laGbArticular)
        self.navLblStartPose_26.setGeometry(QtCore.QRect(320, 300, 21, 17))
        self.navLblStartPose_26.setObjectName("navLblStartPose_26")
        self.laRbSendTrajectory = QtWidgets.QRadioButton(self.tab_2)
        self.laRbSendTrajectory.setGeometry(QtCore.QRect(160, 340, 151, 21))
        self.laRbSendTrajectory.setChecked(True)
        self.laRbSendTrajectory.setObjectName("laRbSendTrajectory")
        self.laRbSendSinglePose = QtWidgets.QRadioButton(self.tab_2)
        self.laRbSendSinglePose.setGeometry(QtCore.QRect(10, 340, 151, 21))
        self.laRbSendSinglePose.setChecked(False)
        self.laRbSendSinglePose.setObjectName("laRbSendSinglePose")
        self.laPbVoltage = QtWidgets.QProgressBar(self.tab_2)
        self.laPbVoltage.setGeometry(QtCore.QRect(460, 370, 118, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.laPbVoltage.setPalette(palette)
        self.laPbVoltage.setStyleSheet("QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: #FF0000;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: rgb(115, 210, 22);\n"
"     width: 20px;\n"
" }")
        self.laPbVoltage.setMinimum(100)
        self.laPbVoltage.setMaximum(126)
        self.laPbVoltage.setProperty("value", 100)
        self.laPbVoltage.setTextVisible(False)
        self.laPbVoltage.setObjectName("laPbVoltage")
        self.laLblVoltage = QtWidgets.QLabel(self.tab_2)
        self.laLblVoltage.setGeometry(QtCore.QRect(580, 360, 81, 41))
        self.laLblVoltage.setStyleSheet("font: 24pt \"Ubuntu\";")
        self.laLblVoltage.setTextFormat(QtCore.Qt.RichText)
        self.laLblVoltage.setScaledContents(False)
        self.laLblVoltage.setWordWrap(False)
        self.laLblVoltage.setOpenExternalLinks(False)
        self.laLblVoltage.setObjectName("laLblVoltage")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(380, 370, 70, 17))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.raGbArticular = QtWidgets.QGroupBox(self.tab_3)
        self.raGbArticular.setGeometry(QtCore.QRect(310, 10, 351, 321))
        self.raGbArticular.setObjectName("raGbArticular")
        self.raTxtAngles5 = QtWidgets.QDoubleSpinBox(self.raGbArticular)
        self.raTxtAngles5.setGeometry(QtCore.QRect(219, 30, 121, 31))
        self.raTxtAngles5.setKeyboardTracking(False)
        self.raTxtAngles5.setDecimals(4)
        self.raTxtAngles5.setMinimum(-3.1416)
        self.raTxtAngles5.setMaximum(3.1416)
        self.raTxtAngles5.setSingleStep(0.1)
        self.raTxtAngles5.setObjectName("raTxtAngles5")
        self.raTxtAngles1 = QtWidgets.QDoubleSpinBox(self.raGbArticular)
        self.raTxtAngles1.setGeometry(QtCore.QRect(39, 30, 121, 31))
        self.raTxtAngles1.setKeyboardTracking(False)
        self.raTxtAngles1.setDecimals(4)
        self.raTxtAngles1.setMinimum(-3.1416)
        self.raTxtAngles1.setMaximum(3.1416)
        self.raTxtAngles1.setSingleStep(0.1)
        self.raTxtAngles1.setObjectName("raTxtAngles1")
        self.raTxtAngles4 = QtWidgets.QDoubleSpinBox(self.raGbArticular)
        self.raTxtAngles4.setGeometry(QtCore.QRect(40, 150, 121, 31))
        self.raTxtAngles4.setKeyboardTracking(False)
        self.raTxtAngles4.setDecimals(4)
        self.raTxtAngles4.setMinimum(-3.1416)
        self.raTxtAngles4.setMaximum(3.1416)
        self.raTxtAngles4.setSingleStep(0.1)
        self.raTxtAngles4.setObjectName("raTxtAngles4")
        self.laLblAngles2_4 = QtWidgets.QLabel(self.raGbArticular)
        self.laLblAngles2_4.setGeometry(QtCore.QRect(10, 80, 41, 17))
        self.laLblAngles2_4.setObjectName("laLblAngles2_4")
        self.laLblAngles6_8 = QtWidgets.QLabel(self.raGbArticular)
        self.laLblAngles6_8.setGeometry(QtCore.QRect(180, 80, 41, 17))
        self.laLblAngles6_8.setObjectName("laLblAngles6_8")
        self.laLblAngles5_4 = QtWidgets.QLabel(self.raGbArticular)
        self.laLblAngles5_4.setGeometry(QtCore.QRect(180, 40, 41, 17))
        self.laLblAngles5_4.setObjectName("laLblAngles5_4")
        self.raTxtAngles6 = QtWidgets.QDoubleSpinBox(self.raGbArticular)
        self.raTxtAngles6.setGeometry(QtCore.QRect(219, 70, 121, 31))
        self.raTxtAngles6.setKeyboardTracking(False)
        self.raTxtAngles6.setDecimals(4)
        self.raTxtAngles6.setMinimum(-3.1416)
        self.raTxtAngles6.setMaximum(3.1416)
        self.raTxtAngles6.setSingleStep(0.1)
        self.raTxtAngles6.setObjectName("raTxtAngles6")
        self.raTxtAngles2 = QtWidgets.QDoubleSpinBox(self.raGbArticular)
        self.raTxtAngles2.setGeometry(QtCore.QRect(39, 70, 121, 31))
        self.raTxtAngles2.setKeyboardTracking(False)
        self.raTxtAngles2.setDecimals(4)
        self.raTxtAngles2.setMinimum(-3.1416)
        self.raTxtAngles2.setMaximum(3.1416)
        self.raTxtAngles2.setSingleStep(0.1)
        self.raTxtAngles2.setProperty("value", 0.0)
        self.raTxtAngles2.setObjectName("raTxtAngles2")
        self.raTxtAngles7 = QtWidgets.QDoubleSpinBox(self.raGbArticular)
        self.raTxtAngles7.setGeometry(QtCore.QRect(219, 110, 121, 31))
        self.raTxtAngles7.setKeyboardTracking(False)
        self.raTxtAngles7.setDecimals(4)
        self.raTxtAngles7.setMinimum(-3.1416)
        self.raTxtAngles7.setMaximum(3.1416)
        self.raTxtAngles7.setSingleStep(0.1)
        self.raTxtAngles7.setObjectName("raTxtAngles7")
        self.laLblAngles4_4 = QtWidgets.QLabel(self.raGbArticular)
        self.laLblAngles4_4.setGeometry(QtCore.QRect(10, 160, 41, 17))
        self.laLblAngles4_4.setObjectName("laLblAngles4_4")
        self.raTxtAngles3 = QtWidgets.QDoubleSpinBox(self.raGbArticular)
        self.raTxtAngles3.setGeometry(QtCore.QRect(39, 110, 121, 31))
        self.raTxtAngles3.setKeyboardTracking(False)
        self.raTxtAngles3.setDecimals(4)
        self.raTxtAngles3.setMinimum(-3.1416)
        self.raTxtAngles3.setMaximum(3.1416)
        self.raTxtAngles3.setSingleStep(0.1)
        self.raTxtAngles3.setObjectName("raTxtAngles3")
        self.laLblAngles1_4 = QtWidgets.QLabel(self.raGbArticular)
        self.laLblAngles1_4.setGeometry(QtCore.QRect(10, 40, 41, 17))
        self.laLblAngles1_4.setObjectName("laLblAngles1_4")
        self.laLblAngles3_4 = QtWidgets.QLabel(self.raGbArticular)
        self.laLblAngles3_4.setGeometry(QtCore.QRect(10, 120, 41, 17))
        self.laLblAngles3_4.setObjectName("laLblAngles3_4")
        self.raTxtArticularGoal = QtWidgets.QLineEdit(self.raGbArticular)
        self.raTxtArticularGoal.setGeometry(QtCore.QRect(50, 220, 291, 31))
        self.raTxtArticularGoal.setText("")
        self.raTxtArticularGoal.setObjectName("raTxtArticularGoal")
        self.hdLblHeadPoseLbl_5 = QtWidgets.QLabel(self.raGbArticular)
        self.hdLblHeadPoseLbl_5.setGeometry(QtCore.QRect(10, 230, 51, 16))
        self.hdLblHeadPoseLbl_5.setObjectName("hdLblHeadPoseLbl_5")
        self.laLblAngles6_9 = QtWidgets.QLabel(self.raGbArticular)
        self.laLblAngles6_9.setGeometry(QtCore.QRect(180, 160, 41, 17))
        self.laLblAngles6_9.setObjectName("laLblAngles6_9")
        self.raTxtAnglesG = QtWidgets.QDoubleSpinBox(self.raGbArticular)
        self.raTxtAnglesG.setGeometry(QtCore.QRect(220, 150, 121, 31))
        self.raTxtAnglesG.setKeyboardTracking(False)
        self.raTxtAnglesG.setDecimals(4)
        self.raTxtAnglesG.setMinimum(-3.1416)
        self.raTxtAnglesG.setMaximum(3.1416)
        self.raTxtAnglesG.setSingleStep(0.1)
        self.raTxtAnglesG.setObjectName("raTxtAnglesG")
        self.laLblAngles0_5 = QtWidgets.QLabel(self.raGbArticular)
        self.laLblAngles0_5.setGeometry(QtCore.QRect(180, 120, 41, 17))
        self.laLblAngles0_5.setObjectName("laLblAngles0_5")
        self.navLblStartPose_28 = QtWidgets.QLabel(self.raGbArticular)
        self.navLblStartPose_28.setGeometry(QtCore.QRect(220, 300, 21, 17))
        self.navLblStartPose_28.setObjectName("navLblStartPose_28")
        self.navLblStartPose_29 = QtWidgets.QLabel(self.raGbArticular)
        self.navLblStartPose_29.setGeometry(QtCore.QRect(20, 300, 21, 17))
        self.navLblStartPose_29.setObjectName("navLblStartPose_29")
        self.navLblStartPose_16 = QtWidgets.QLabel(self.raGbArticular)
        self.navLblStartPose_16.setGeometry(QtCore.QRect(10, 260, 71, 17))
        self.navLblStartPose_16.setObjectName("navLblStartPose_16")
        self.navLblStartPose_21 = QtWidgets.QLabel(self.raGbArticular)
        self.navLblStartPose_21.setGeometry(QtCore.QRect(120, 300, 21, 17))
        self.navLblStartPose_21.setObjectName("navLblStartPose_21")
        self.raLblCurrentQ6 = QtWidgets.QLabel(self.raGbArticular)
        self.raLblCurrentQ6.setGeometry(QtCore.QRect(260, 280, 41, 17))
        self.raLblCurrentQ6.setObjectName("raLblCurrentQ6")
        self.navLblStartPose_30 = QtWidgets.QLabel(self.raGbArticular)
        self.navLblStartPose_30.setGeometry(QtCore.QRect(170, 300, 21, 17))
        self.navLblStartPose_30.setObjectName("navLblStartPose_30")
        self.raLblCurrentQ2 = QtWidgets.QLabel(self.raGbArticular)
        self.raLblCurrentQ2.setGeometry(QtCore.QRect(60, 280, 41, 17))
        self.raLblCurrentQ2.setObjectName("raLblCurrentQ2")
        self.raLblCurrentQ4 = QtWidgets.QLabel(self.raGbArticular)
        self.raLblCurrentQ4.setGeometry(QtCore.QRect(160, 280, 41, 17))
        self.raLblCurrentQ4.setObjectName("raLblCurrentQ4")
        self.navLblStartPose_22 = QtWidgets.QLabel(self.raGbArticular)
        self.navLblStartPose_22.setGeometry(QtCore.QRect(70, 300, 21, 17))
        self.navLblStartPose_22.setObjectName("navLblStartPose_22")
        self.raLblCurrentQ3 = QtWidgets.QLabel(self.raGbArticular)
        self.raLblCurrentQ3.setGeometry(QtCore.QRect(110, 280, 41, 17))
        self.raLblCurrentQ3.setObjectName("raLblCurrentQ3")
        self.raLblCurrentQ1 = QtWidgets.QLabel(self.raGbArticular)
        self.raLblCurrentQ1.setGeometry(QtCore.QRect(10, 280, 41, 17))
        self.raLblCurrentQ1.setObjectName("raLblCurrentQ1")
        self.raLblCurrentQ5 = QtWidgets.QLabel(self.raGbArticular)
        self.raLblCurrentQ5.setGeometry(QtCore.QRect(210, 280, 41, 17))
        self.raLblCurrentQ5.setObjectName("raLblCurrentQ5")
        self.navLblStartPose_31 = QtWidgets.QLabel(self.raGbArticular)
        self.navLblStartPose_31.setGeometry(QtCore.QRect(270, 300, 21, 17))
        self.navLblStartPose_31.setObjectName("navLblStartPose_31")
        self.raLblCurrentQ7 = QtWidgets.QLabel(self.raGbArticular)
        self.raLblCurrentQ7.setGeometry(QtCore.QRect(310, 280, 41, 17))
        self.raLblCurrentQ7.setObjectName("raLblCurrentQ7")
        self.navLblStartPose_32 = QtWidgets.QLabel(self.raGbArticular)
        self.navLblStartPose_32.setGeometry(QtCore.QRect(320, 300, 21, 17))
        self.navLblStartPose_32.setObjectName("navLblStartPose_32")
        self.gbNavig_3 = QtWidgets.QGroupBox(self.tab_3)
        self.gbNavig_3.setGeometry(QtCore.QRect(0, 10, 311, 321))
        self.gbNavig_3.setStyleSheet("")
        self.gbNavig_3.setObjectName("gbNavig_3")
        self.raTxtCartesianGoal = QtWidgets.QLineEdit(self.gbNavig_3)
        self.raTxtCartesianGoal.setGeometry(QtCore.QRect(50, 220, 251, 31))
        self.raTxtCartesianGoal.setObjectName("raTxtCartesianGoal")
        self.navLblStartPose_9 = QtWidgets.QLabel(self.gbNavig_3)
        self.navLblStartPose_9.setGeometry(QtCore.QRect(10, 230, 51, 17))
        self.navLblStartPose_9.setObjectName("navLblStartPose_9")
        self.raBtnXp = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnXp.setGeometry(QtCore.QRect(140, 40, 50, 40))
        self.raBtnXp.setIconSize(QtCore.QSize(32, 32))
        self.raBtnXp.setObjectName("raBtnXp")
        self.raBtnYp = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnYp.setGeometry(QtCore.QRect(80, 20, 50, 40))
        self.raBtnYp.setIconSize(QtCore.QSize(32, 32))
        self.raBtnYp.setObjectName("raBtnYp")
        self.raBtnXm = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnXm.setGeometry(QtCore.QRect(20, 40, 50, 40))
        self.raBtnXm.setIconSize(QtCore.QSize(32, 32))
        self.raBtnXm.setObjectName("raBtnXm")
        self.raBtnYm = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnYm.setGeometry(QtCore.QRect(80, 70, 50, 40))
        self.raBtnYm.setIconSize(QtCore.QSize(32, 32))
        self.raBtnYm.setObjectName("raBtnYm")
        self.raLblCurrentX = QtWidgets.QLabel(self.gbNavig_3)
        self.raLblCurrentX.setGeometry(QtCore.QRect(10, 280, 41, 17))
        self.raLblCurrentX.setObjectName("raLblCurrentX")
        self.raBtnZp = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnZp.setGeometry(QtCore.QRect(220, 20, 50, 40))
        self.raBtnZp.setIconSize(QtCore.QSize(32, 32))
        self.raBtnZp.setObjectName("raBtnZp")
        self.raBtnZm = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnZm.setGeometry(QtCore.QRect(220, 70, 50, 40))
        self.raBtnZm.setIconSize(QtCore.QSize(32, 32))
        self.raBtnZm.setObjectName("raBtnZm")
        self.navLblStartPose_10 = QtWidgets.QLabel(self.gbNavig_3)
        self.navLblStartPose_10.setGeometry(QtCore.QRect(20, 300, 21, 17))
        self.navLblStartPose_10.setObjectName("navLblStartPose_10")
        self.navLblStartPose_11 = QtWidgets.QLabel(self.gbNavig_3)
        self.navLblStartPose_11.setGeometry(QtCore.QRect(70, 300, 21, 17))
        self.navLblStartPose_11.setObjectName("navLblStartPose_11")
        self.navLblStartPose_12 = QtWidgets.QLabel(self.gbNavig_3)
        self.navLblStartPose_12.setGeometry(QtCore.QRect(120, 300, 21, 17))
        self.navLblStartPose_12.setObjectName("navLblStartPose_12")
        self.navLblStartPose_13 = QtWidgets.QLabel(self.gbNavig_3)
        self.navLblStartPose_13.setGeometry(QtCore.QRect(170, 300, 21, 17))
        self.navLblStartPose_13.setObjectName("navLblStartPose_13")
        self.navLblStartPose_17 = QtWidgets.QLabel(self.gbNavig_3)
        self.navLblStartPose_17.setGeometry(QtCore.QRect(270, 300, 21, 17))
        self.navLblStartPose_17.setObjectName("navLblStartPose_17")
        self.navLblStartPose_18 = QtWidgets.QLabel(self.gbNavig_3)
        self.navLblStartPose_18.setGeometry(QtCore.QRect(220, 300, 21, 17))
        self.navLblStartPose_18.setObjectName("navLblStartPose_18")
        self.raLblCurrentY = QtWidgets.QLabel(self.gbNavig_3)
        self.raLblCurrentY.setGeometry(QtCore.QRect(60, 280, 41, 17))
        self.raLblCurrentY.setObjectName("raLblCurrentY")
        self.raLblCurrentZ = QtWidgets.QLabel(self.gbNavig_3)
        self.raLblCurrentZ.setGeometry(QtCore.QRect(110, 280, 41, 17))
        self.raLblCurrentZ.setObjectName("raLblCurrentZ")
        self.raLblCurrentRoll = QtWidgets.QLabel(self.gbNavig_3)
        self.raLblCurrentRoll.setGeometry(QtCore.QRect(160, 280, 41, 17))
        self.raLblCurrentRoll.setObjectName("raLblCurrentRoll")
        self.raLblCurrentPitch = QtWidgets.QLabel(self.gbNavig_3)
        self.raLblCurrentPitch.setGeometry(QtCore.QRect(210, 280, 41, 17))
        self.raLblCurrentPitch.setObjectName("raLblCurrentPitch")
        self.raLblCurrentYaw = QtWidgets.QLabel(self.gbNavig_3)
        self.raLblCurrentYaw.setGeometry(QtCore.QRect(260, 280, 41, 17))
        self.raLblCurrentYaw.setObjectName("raLblCurrentYaw")
        self.navLblStartPose_33 = QtWidgets.QLabel(self.gbNavig_3)
        self.navLblStartPose_33.setGeometry(QtCore.QRect(10, 260, 71, 17))
        self.navLblStartPose_33.setObjectName("navLblStartPose_33")
        self.raBtnRollp = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnRollp.setGeometry(QtCore.QRect(40, 130, 50, 31))
        self.raBtnRollp.setIconSize(QtCore.QSize(32, 32))
        self.raBtnRollp.setObjectName("raBtnRollp")
        self.raBtnRollm = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnRollm.setGeometry(QtCore.QRect(40, 170, 50, 31))
        self.raBtnRollm.setIconSize(QtCore.QSize(32, 32))
        self.raBtnRollm.setObjectName("raBtnRollm")
        self.raBtnPitchp = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnPitchp.setGeometry(QtCore.QRect(120, 130, 50, 31))
        self.raBtnPitchp.setIconSize(QtCore.QSize(32, 32))
        self.raBtnPitchp.setObjectName("raBtnPitchp")
        self.raBtnPitchm = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnPitchm.setGeometry(QtCore.QRect(120, 170, 50, 31))
        self.raBtnPitchm.setIconSize(QtCore.QSize(32, 32))
        self.raBtnPitchm.setObjectName("raBtnPitchm")
        self.raBtnYawp = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnYawp.setGeometry(QtCore.QRect(200, 130, 50, 31))
        self.raBtnYawp.setIconSize(QtCore.QSize(32, 32))
        self.raBtnYawp.setObjectName("raBtnYawp")
        self.raBtnYawm = QtWidgets.QPushButton(self.gbNavig_3)
        self.raBtnYawm.setGeometry(QtCore.QRect(200, 170, 50, 31))
        self.raBtnYawm.setIconSize(QtCore.QSize(32, 32))
        self.raBtnYawm.setObjectName("raBtnYawm")
        self.raRbSendTrajectory = QtWidgets.QRadioButton(self.tab_3)
        self.raRbSendTrajectory.setGeometry(QtCore.QRect(160, 340, 151, 21))
        self.raRbSendTrajectory.setChecked(True)
        self.raRbSendTrajectory.setObjectName("raRbSendTrajectory")
        self.raRbSendSinglePose = QtWidgets.QRadioButton(self.tab_3)
        self.raRbSendSinglePose.setGeometry(QtCore.QRect(10, 340, 151, 21))
        self.raRbSendSinglePose.setObjectName("raRbSendSinglePose")
        self.raPbVoltage = QtWidgets.QProgressBar(self.tab_3)
        self.raPbVoltage.setGeometry(QtCore.QRect(460, 370, 118, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.raPbVoltage.setFont(font)
        self.raPbVoltage.setAutoFillBackground(False)
        self.raPbVoltage.setStyleSheet("QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: #FF0000;\n"
" }\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: rgb(115, 210, 22);\n"
"     width: 20px;\n"
" }")
        self.raPbVoltage.setMinimum(100)
        self.raPbVoltage.setMaximum(126)
        self.raPbVoltage.setProperty("value", 100)
        self.raPbVoltage.setTextVisible(False)
        self.raPbVoltage.setObjectName("raPbVoltage")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(380, 370, 61, 17))
        self.label_7.setObjectName("label_7")
        self.raLblVoltage = QtWidgets.QLabel(self.tab_3)
        self.raLblVoltage.setGeometry(QtCore.QRect(580, 370, 71, 31))
        self.raLblVoltage.setStyleSheet("font: 24pt \"Ubuntu\";")
        self.raLblVoltage.setObjectName("raLblVoltage")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.btnFwd)
        MainWindow.setTabOrder(self.btnFwd, self.btnBwd)
        MainWindow.setTabOrder(self.btnBwd, self.btnTurnLeft)
        MainWindow.setTabOrder(self.btnTurnLeft, self.btnTurnRight)
        MainWindow.setTabOrder(self.btnTurnRight, self.txtLinearX)
        MainWindow.setTabOrder(self.txtLinearX, self.txtLinearY)
        MainWindow.setTabOrder(self.txtLinearY, self.txtAngular)
        MainWindow.setTabOrder(self.txtAngular, self.btnCmdVel)
        MainWindow.setTabOrder(self.btnCmdVel, self.navTxtStartPose)
        MainWindow.setTabOrder(self.navTxtStartPose, self.navTxtGoalPose)
        MainWindow.setTabOrder(self.navTxtGoalPose, self.navBtnCalcPath)
        MainWindow.setTabOrder(self.navBtnCalcPath, self.navBtnExecPath)
        MainWindow.setTabOrder(self.navBtnExecPath, self.navTxtMove)
        MainWindow.setTabOrder(self.navTxtMove, self.btnStop)
        MainWindow.setTabOrder(self.btnStop, self.hdTxtPan)
        MainWindow.setTabOrder(self.hdTxtPan, self.hdTxtTilt)
        MainWindow.setTabOrder(self.hdTxtTilt, self.hdTxtPredefined)
        MainWindow.setTabOrder(self.hdTxtPredefined, self.torTxtPos)
        MainWindow.setTabOrder(self.torTxtPos, self.torTxtPredefined)
        MainWindow.setTabOrder(self.torTxtPredefined, self.spgTxtSay)
        MainWindow.setTabOrder(self.spgTxtSay, self.sprTxtFakeRecog)
        MainWindow.setTabOrder(self.sprTxtFakeRecog, self.visBtnFindLines)
        MainWindow.setTabOrder(self.visBtnFindLines, self.visTxtTrainObject)
        MainWindow.setTabOrder(self.visTxtTrainObject, self.visBtnRecogObjects)
        MainWindow.setTabOrder(self.visBtnRecogObjects, self.visTxtRecognizeObject)
        MainWindow.setTabOrder(self.visTxtRecognizeObject, self.tksBtnApproachTable)
        MainWindow.setTabOrder(self.tksBtnApproachTable, self.tksTxtTakeObject)
        MainWindow.setTabOrder(self.tksTxtTakeObject, self.tksBtnTakeObject)
        MainWindow.setTabOrder(self.tksBtnTakeObject, self.tksBtnApproachTable_2)
        MainWindow.setTabOrder(self.tksBtnApproachTable_2, self.laBtnXm)
        MainWindow.setTabOrder(self.laBtnXm, self.laBtnXp)
        MainWindow.setTabOrder(self.laBtnXp, self.laBtnYp)
        MainWindow.setTabOrder(self.laBtnYp, self.laBtnYm)
        MainWindow.setTabOrder(self.laBtnYm, self.laBtnZp)
        MainWindow.setTabOrder(self.laBtnZp, self.laBtnZm)
        MainWindow.setTabOrder(self.laBtnZm, self.laBtnRollp)
        MainWindow.setTabOrder(self.laBtnRollp, self.laBtnRollm)
        MainWindow.setTabOrder(self.laBtnRollm, self.laBtnPitchp)
        MainWindow.setTabOrder(self.laBtnPitchp, self.laBtnPitchm)
        MainWindow.setTabOrder(self.laBtnPitchm, self.laBtnYawp)
        MainWindow.setTabOrder(self.laBtnYawp, self.laBtnYawm)
        MainWindow.setTabOrder(self.laBtnYawm, self.laTxtCartesianGoal)
        MainWindow.setTabOrder(self.laTxtCartesianGoal, self.laTxtAngles1)
        MainWindow.setTabOrder(self.laTxtAngles1, self.laTxtAngles2)
        MainWindow.setTabOrder(self.laTxtAngles2, self.laTxtAngles3)
        MainWindow.setTabOrder(self.laTxtAngles3, self.laTxtAngles4)
        MainWindow.setTabOrder(self.laTxtAngles4, self.laTxtAngles5)
        MainWindow.setTabOrder(self.laTxtAngles5, self.laTxtAngles6)
        MainWindow.setTabOrder(self.laTxtAngles6, self.laTxtAngles7)
        MainWindow.setTabOrder(self.laTxtAngles7, self.laTxtAnglesG)
        MainWindow.setTabOrder(self.laTxtAnglesG, self.laTxtArticularGoal)
        MainWindow.setTabOrder(self.laTxtArticularGoal, self.laRbSendSinglePose)
        MainWindow.setTabOrder(self.laRbSendSinglePose, self.laRbSendTrajectory)
        MainWindow.setTabOrder(self.laRbSendTrajectory, self.raBtnXm)
        MainWindow.setTabOrder(self.raBtnXm, self.raBtnXp)
        MainWindow.setTabOrder(self.raBtnXp, self.raBtnYp)
        MainWindow.setTabOrder(self.raBtnYp, self.raBtnYm)
        MainWindow.setTabOrder(self.raBtnYm, self.raBtnZp)
        MainWindow.setTabOrder(self.raBtnZp, self.raBtnZm)
        MainWindow.setTabOrder(self.raBtnZm, self.raBtnRollp)
        MainWindow.setTabOrder(self.raBtnRollp, self.raBtnRollm)
        MainWindow.setTabOrder(self.raBtnRollm, self.raBtnPitchp)
        MainWindow.setTabOrder(self.raBtnPitchp, self.raBtnPitchm)
        MainWindow.setTabOrder(self.raBtnPitchm, self.raBtnYawp)
        MainWindow.setTabOrder(self.raBtnYawp, self.raBtnYawm)
        MainWindow.setTabOrder(self.raBtnYawm, self.raTxtCartesianGoal)
        MainWindow.setTabOrder(self.raTxtCartesianGoal, self.raTxtAngles1)
        MainWindow.setTabOrder(self.raTxtAngles1, self.raTxtAngles2)
        MainWindow.setTabOrder(self.raTxtAngles2, self.raTxtAngles3)
        MainWindow.setTabOrder(self.raTxtAngles3, self.raTxtAngles4)
        MainWindow.setTabOrder(self.raTxtAngles4, self.raTxtAngles5)
        MainWindow.setTabOrder(self.raTxtAngles5, self.raTxtAngles6)
        MainWindow.setTabOrder(self.raTxtAngles6, self.raTxtAngles7)
        MainWindow.setTabOrder(self.raTxtAngles7, self.raTxtAnglesG)
        MainWindow.setTabOrder(self.raTxtAnglesG, self.raTxtArticularGoal)
        MainWindow.setTabOrder(self.raTxtArticularGoal, self.raRbSendSinglePose)
        MainWindow.setTabOrder(self.raRbSendSinglePose, self.raRbSendTrajectory)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mobile Robots  - Ramiro Leonardo"))
        self.gbNavig.setTitle(_translate("MainWindow", "Mobile base and navigation"))
        self.navBtnExecPath.setText(_translate("MainWindow", "Exec Path"))
        self.navLblStartPose.setText(_translate("MainWindow", "Start Pose:"))
        self.navBtnCalcPath.setText(_translate("MainWindow", "Calc Path"))
        self.navLblGoalPose.setText(_translate("MainWindow", "Goal Pose:"))
        self.navLblMove.setText(_translate("MainWindow", "Simple Move:"))
        self.txtLinearX.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "X:"))
        self.txtAngular.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Y:"))
        self.label_4.setText(_translate("MainWindow", "W:"))
        self.btnCmdVel.setText(_translate("MainWindow", "Move Base"))
        self.txtLinearY.setText(_translate("MainWindow", "0"))
        self.btnStop.setText(_translate("MainWindow", "S T O P "))
        self.gbHead.setTitle(_translate("MainWindow", "Head"))
        self.hdLblPan.setText(_translate("MainWindow", "Pan:"))
        self.label.setText(_translate("MainWindow", "Tilt:"))
        self.hdLblHeadPoseLbl.setText(_translate("MainWindow", "Predefined:"))
        self.gbSpeech.setTitle(_translate("MainWindow", "Speech synthesis and recognition"))
        self.spgLabel.setText(_translate("MainWindow", "Say:"))
        self.sprLabel.setText(_translate("MainWindow", "Fake Reco:"))
        self.laLblAngles6_5.setText(_translate("MainWindow", "Last Recog:"))
        self.sprLblLastRecog.setText(_translate("MainWindow", "Please bring me the orange juice from the kitchen"))
        self.gbHead_2.setTitle(_translate("MainWindow", "Torso"))
        self.hdLblPan_2.setText(_translate("MainWindow", "Spine:"))
        self.hdLblHeadPoseLbl_2.setText(_translate("MainWindow", "Predefined:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("MainWindow", "General"))
        self.visBtnFindLines.setText(_translate("MainWindow", "Find Lines"))
        self.label_5.setText(_translate("MainWindow", "Train Object:"))
        self.visBtnRecogObjects.setText(_translate("MainWindow", "Recognize Objects"))
        self.visBtnFindHoriPlanes.setText(_translate("MainWindow", "Find Horizontal Planes"))
        self.visBtnPointsAbovePlane.setText(_translate("MainWindow", "Get Points\n"
"Above a Plane"))
        self.visBtnEnableHumanPose.setText(_translate("MainWindow", "Enable\n"
"Human Pose Det"))
        self.hriBtnEnableFollowHuman.setText(_translate("MainWindow", "Enable\n"
"Follow Human"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Vision"))
        self.tksBtnApproachTable.setText(_translate("MainWindow", "Approach to \n"
"Table"))
        self.label_6.setText(_translate("MainWindow", "Take Object:"))
        self.tksBtnTakeObject.setText(_translate("MainWindow", "Take"))
        self.tksBtnApproachTable_2.setText(_translate("MainWindow", "Memorize\n"
"Person"))
        self.label_9.setText(_translate("MainWindow", "　　∧,,∧ \n"
"　 (,,・∀・) \n"
"～(_ｕ,ｕﾉ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSimpleTasks), _translate("MainWindow", "Simple Tasks"))
        self.gbNavig_2.setTitle(_translate("MainWindow", "Left Arm Cartesian"))
        self.navLblStartPose_2.setText(_translate("MainWindow", "Goal:"))
        self.laBtnXp.setText(_translate("MainWindow", "+X"))
        self.laBtnYp.setText(_translate("MainWindow", "+Y"))
        self.laBtnXm.setText(_translate("MainWindow", "-X"))
        self.laBtnYm.setText(_translate("MainWindow", "-Y"))
        self.laLblCurrentX.setText(_translate("MainWindow", "0.000"))
        self.laBtnZp.setText(_translate("MainWindow", "+Z"))
        self.laBtnZm.setText(_translate("MainWindow", "-Z"))
        self.navLblStartPose_3.setText(_translate("MainWindow", "X"))
        self.navLblStartPose_4.setText(_translate("MainWindow", "Y"))
        self.navLblStartPose_5.setText(_translate("MainWindow", "Z"))
        self.navLblStartPose_6.setText(_translate("MainWindow", "R"))
        self.navLblStartPose_7.setText(_translate("MainWindow", "Y"))
        self.navLblStartPose_8.setText(_translate("MainWindow", "P"))
        self.laLblCurrentY.setText(_translate("MainWindow", "0.000"))
        self.laLblCurrentZ.setText(_translate("MainWindow", "0.000"))
        self.laLblCurrentRoll.setText(_translate("MainWindow", "0.000"))
        self.laLblCurrentPitch.setText(_translate("MainWindow", "0.000"))
        self.laLblCurrentYaw.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_14.setText(_translate("MainWindow", "Current:"))
        self.laBtnRollp.setText(_translate("MainWindow", "+Roll"))
        self.laBtnRollm.setText(_translate("MainWindow", "-Roll"))
        self.laBtnPitchp.setText(_translate("MainWindow", "+Pitch"))
        self.laBtnPitchm.setText(_translate("MainWindow", "-Pitch"))
        self.laBtnYawp.setText(_translate("MainWindow", "+Yaw"))
        self.laBtnYawm.setText(_translate("MainWindow", "-Yaw"))
        self.laGbArticular.setTitle(_translate("MainWindow", "Left Arm Articular"))
        self.laLblAngles2_3.setText(_translate("MainWindow", "q2:"))
        self.laLblAngles6_6.setText(_translate("MainWindow", "q6:"))
        self.laLblAngles5_3.setText(_translate("MainWindow", "q5:"))
        self.laLblAngles4_3.setText(_translate("MainWindow", "q4:"))
        self.laLblAngles1_3.setText(_translate("MainWindow", "q1:"))
        self.laLblAngles3_3.setText(_translate("MainWindow", "q3:"))
        self.hdLblHeadPoseLbl_4.setText(_translate("MainWindow", "Goal:"))
        self.laLblAngles6_7.setText(_translate("MainWindow", "Grip:"))
        self.laLblAngles0_4.setText(_translate("MainWindow", "q7:"))
        self.navLblStartPose_27.setText(_translate("MainWindow", "q5"))
        self.navLblStartPose_23.setText(_translate("MainWindow", "q1 "))
        self.navLblStartPose_15.setText(_translate("MainWindow", "Current:"))
        self.navLblStartPose_20.setText(_translate("MainWindow", "q3"))
        self.laLblCurrentQ6.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_24.setText(_translate("MainWindow", "q4"))
        self.laLblCurrentQ2.setText(_translate("MainWindow", "0.000"))
        self.laLblCurrentQ4.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_19.setText(_translate("MainWindow", "q2"))
        self.laLblCurrentQ3.setText(_translate("MainWindow", "0.000"))
        self.laLblCurrentQ1.setText(_translate("MainWindow", "0.000"))
        self.laLblCurrentQ5.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_25.setText(_translate("MainWindow", "q6"))
        self.laLblCurrentQ7.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_26.setText(_translate("MainWindow", "q7"))
        self.laRbSendTrajectory.setText(_translate("MainWindow", "Send &Trajectory"))
        self.laRbSendSinglePose.setText(_translate("MainWindow", "Se&nd Single Pose"))
        self.laLblVoltage.setText(_translate("MainWindow", "0.0 V"))
        self.label_8.setText(_translate("MainWindow", "Voltage:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Left Arm"))
        self.raGbArticular.setTitle(_translate("MainWindow", "Right Arm Articular"))
        self.laLblAngles2_4.setText(_translate("MainWindow", "q2:"))
        self.laLblAngles6_8.setText(_translate("MainWindow", "q6:"))
        self.laLblAngles5_4.setText(_translate("MainWindow", "q5:"))
        self.laLblAngles4_4.setText(_translate("MainWindow", "q4:"))
        self.laLblAngles1_4.setText(_translate("MainWindow", "q1:"))
        self.laLblAngles3_4.setText(_translate("MainWindow", "q3:"))
        self.hdLblHeadPoseLbl_5.setText(_translate("MainWindow", "Goal:"))
        self.laLblAngles6_9.setText(_translate("MainWindow", "Grip:"))
        self.laLblAngles0_5.setText(_translate("MainWindow", "q7:"))
        self.navLblStartPose_28.setText(_translate("MainWindow", "q5"))
        self.navLblStartPose_29.setText(_translate("MainWindow", "q1 "))
        self.navLblStartPose_16.setText(_translate("MainWindow", "Current:"))
        self.navLblStartPose_21.setText(_translate("MainWindow", "q3"))
        self.raLblCurrentQ6.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_30.setText(_translate("MainWindow", "q4"))
        self.raLblCurrentQ2.setText(_translate("MainWindow", "0.000"))
        self.raLblCurrentQ4.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_22.setText(_translate("MainWindow", "q2"))
        self.raLblCurrentQ3.setText(_translate("MainWindow", "0.000"))
        self.raLblCurrentQ1.setText(_translate("MainWindow", "0.000"))
        self.raLblCurrentQ5.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_31.setText(_translate("MainWindow", "q6"))
        self.raLblCurrentQ7.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_32.setText(_translate("MainWindow", "q7"))
        self.gbNavig_3.setTitle(_translate("MainWindow", "Right Arm Cartesian"))
        self.navLblStartPose_9.setText(_translate("MainWindow", "Goal:"))
        self.raBtnXp.setText(_translate("MainWindow", "+X"))
        self.raBtnYp.setText(_translate("MainWindow", "+Y"))
        self.raBtnXm.setText(_translate("MainWindow", "-X"))
        self.raBtnYm.setText(_translate("MainWindow", "-Y"))
        self.raLblCurrentX.setText(_translate("MainWindow", "0.000"))
        self.raBtnZp.setText(_translate("MainWindow", "+Z"))
        self.raBtnZm.setText(_translate("MainWindow", "-Z"))
        self.navLblStartPose_10.setText(_translate("MainWindow", "X"))
        self.navLblStartPose_11.setText(_translate("MainWindow", "Y"))
        self.navLblStartPose_12.setText(_translate("MainWindow", "Z"))
        self.navLblStartPose_13.setText(_translate("MainWindow", "R"))
        self.navLblStartPose_17.setText(_translate("MainWindow", "Y"))
        self.navLblStartPose_18.setText(_translate("MainWindow", "P"))
        self.raLblCurrentY.setText(_translate("MainWindow", "0.000"))
        self.raLblCurrentZ.setText(_translate("MainWindow", "0.000"))
        self.raLblCurrentRoll.setText(_translate("MainWindow", "0.000"))
        self.raLblCurrentPitch.setText(_translate("MainWindow", "0.000"))
        self.raLblCurrentYaw.setText(_translate("MainWindow", "0.000"))
        self.navLblStartPose_33.setText(_translate("MainWindow", "Current:"))
        self.raBtnRollp.setText(_translate("MainWindow", "+Roll"))
        self.raBtnRollm.setText(_translate("MainWindow", "-Roll"))
        self.raBtnPitchp.setText(_translate("MainWindow", "+Pitch"))
        self.raBtnPitchm.setText(_translate("MainWindow", "-Pitch"))
        self.raBtnYawp.setText(_translate("MainWindow", "+Yaw"))
        self.raBtnYawm.setText(_translate("MainWindow", "-Yaw"))
        self.raRbSendTrajectory.setText(_translate("MainWindow", "Sen&d Trajectory"))
        self.raRbSendSinglePose.setText(_translate("MainWindow", "Se&nd Single Pose"))
        self.label_7.setText(_translate("MainWindow", "Voltage:"))
        self.raLblVoltage.setText(_translate("MainWindow", "0.0 V"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Right Arm"))
